import { ABaseUrl, AoPaymentUrl, CeURl } from "../control/Constant";

let BASE_URL = ABaseUrl;

let $Service_Url = {
  getGenderListPath: BASE_URL + "/api/Genders",
  getCitizenshipType: BASE_URL + "/api/CitizenshipType",
  getNameSuffixPath: BASE_URL + "/api/NameSuffixes",
  getFamilyMemberbyID: BASE_URL + "/api/Member/",
  putUpdateMember: BASE_URL + "/api/Member/update-member-by-id/",
  getFamilybyParentID: BASE_URL + "/api/Member/GetFamilyMembersByParentId/",
  getNonFamilyMember: BASE_URL + "/api/Member/getUserNonFamilyMember/",
  getVeteranData: BASE_URL + "/api/Veteran/get-veteran-by-userid/",
  postAddOccupation: BASE_URL + "/api/Occupation/add-occupation-by-userid/",
  getOccupationbyUserId: BASE_URL + "/api/Occupation/get-occupation-by-userid/",
  putOccupationbyUserId: BASE_URL + "/api/Occupation/update-occupation-by-userid",
  deleteOccupationbyUserId: BASE_URL + "/api/Occupation/delete-occupation-by-userid",
  getRelationshiplist: BASE_URL + "/api/RelationshipType",
  getNotifyContactMapApi:BASE_URL+'/api/NotifyContactMap/getNotifyContactMap',
  deletememberchild:BASE_URL + '/api/Member/delete-member/',
  getFamilyMemberbyID: BASE_URL + "/api/Member/",
  createXmlGenrater:BASE_URL+'/api/XMLGenerator',
  createXmlGenraterDocFile: 'https://documentgeneratorapi.agingoptions.com/document/generate',
  createXmlGenraterDocFileForAsset: 'https://documentgeneratorapi.agingoptions.com/document/generate?target_template=LPL_EP_Beneficiary_Designations_Letter_Repeated&environment=Production',
  generateDocumentsFolder:"https://documentgeneratorapi.agingoptions.com/generated-documents-folder",
  genrateDocumentFile: 'https://documentgeneratorapi.agingoptions.com/generated-documents',
  getDocVersion:'https://documentgeneratorapi.agingoptions.com/generated-documents/versions',
  getAcademyUserData:'https://academyportal.nsplindia.co.in/wp-json/custom/v1/signin?user_email',
  getAvailableDocuments:'https://documentgeneratorapi.agingoptions.com/documents-available',
  postFileFolderUpdate:"/api/2/UserFileCabinet/Update",
  postUploadUserDocumentVersion2:BASE_URL+'/api/2/FileUpload/uploadUserDocuments',
  


  getAllMembersPath: BASE_URL + "/api/Member/get-all-members",
  getAuthTokenPath: BASE_URL + "/api/Authentication/authenticate",
  getAddressTypePath: BASE_URL + "/api/AddressType",
  getCountryListPath: BASE_URL + "/api/Country",
  getContactTypePath: BASE_URL + "/api/ContactType",
  getNumberType: BASE_URL + "/api/CommType",
  getMaritalStatusPath: BASE_URL + "/api/MaritalStatuses",
  getWarTimePeriodPath: BASE_URL + "/api/WarTimePeriod",
  getStatePath: BASE_URL + "/api/State/",
  updateVeteranData: BASE_URL + "/api/Veteran/update-veteran-by-userid/",
  getLoggedInUser: BASE_URL + "/api/User/GetLoggedInUser/",
  postAddMember: BASE_URL + "/api/Member/add-member",
  postAddAddress: BASE_URL + "/api/Address/add-address-by-userid/",
  getAllAddress: BASE_URL + "/api/Address/get-address-by-userid/",
  deleteAddress: BASE_URL + "/api/Address/delete-address-by-userid/",
  deleteContactPath: BASE_URL + "/api/Contact/delete-contact-by-userid/",
  postAddContactAddress: BASE_URL + "/api/Contact/add-contact-by-userid/",
  postAddContactWithOther:
    BASE_URL + "/api/ContactWithOther/add-contactwithother-by-userid/",
  getAllContactOtherPath: BASE_URL + "/api/Contact/get-contact-by-userid/",
  getAllContactOtherPath: BASE_URL + "/api/ContactWithOther/get-contactwithother-by-userid/",
  updateContactDetailsPath: BASE_URL + "/api/Contact/update-contact-by-userid/",
  updateContactWithOtherDetailsPath:
    BASE_URL + "/api/ContactWithOther/update-contactwithother-by-userid",
  getFamilyMembers: BASE_URL + "/api/Member/get-FamilyMembers-by-userid/",
  getFamilyMemberbyID: BASE_URL + "/api/Member/",
  getFamilybyParentID: BASE_URL + "/api/Member/GetFamilyMembersByParentId/",
  getFidMemberByUserId: BASE_URL + "/api/Member/get-FiducairyMembers-by-userid/",
  getDischargeType: BASE_URL + "/api/VDischargeType/",
  postVeteranByUserid: BASE_URL + "/api/Veteran/add-veteran-by-userid/",
  
  getHealthInsPlanType: BASE_URL + "/api/TypePlan/",

  getHealthInsSupPlan: BASE_URL + "/api/SuppPlan/",
  postaddUserInsurance: BASE_URL + "/api/UserInsurance/add-UserInsurance",
  putupdateuserinsurance: BASE_URL + "/api/UserInsurance/Update-UserInsurance",
  getUserInsurance:
BASE_URL + "/api/UserInsurance/get-UserInsurance-by-userid/",
  getSpecialistType: BASE_URL + "/api/SpecialityType",
  postAddPhysician: BASE_URL + "/api/PrimaryCare/add-primarycaremember/",
  getPrimaryPhysician:
    BASE_URL + "/api/PrimaryCare/get-primarycaremembers-by-primaryuserid/",
  getPreconditionType: BASE_URL + "/api/AssetType/get-preconditiontype/",
  getCountyRef: BASE_URL + "/api/CountyRef/GetCountyRef/",
  getUserAgingAsset:
    BASE_URL + "/api/UserAgingAsset/get-UserAgingAsset-by-userid/",
  getOwnerType: BASE_URL + "/api/OwnerType",
  postUseragingAsset: BASE_URL + "/api/UserAgingAsset/add-UserAgingAsset",
  getLiabilityTypes: BASE_URL + "/api/LiabilityType",
  getLiabilityUserTypes: BASE_URL + "/api/UserLiability/",
  postAddLiability: BASE_URL + "/api/UserLiability/add-UserLiability/",
  putAddLiability: BASE_URL + "/api/UserLiability/Update-UserLiability",
  postAddTax: BASE_URL + "/api/UserTax/add-UserTax/",
  getTaxInfo: BASE_URL + "/api/UserTax/",
  upsertTaxInfo: BASE_URL + "/api/UserTax/Upsert-UserTax",
  putTaxInformation:BASE_URL+"/api/UserTax/Delete-UserTax",
  postAddFamilyHistory: BASE_URL + "/api/UserMedHistory/add-UserMedHistory/",
  putUpdateFamilyHistory:
    BASE_URL + "/api/UserMedHistory/Update-UserMedHistory",
  getuserfamilyHistory:
    BASE_URL + "/api/UserMedHistory/get-UserMedHistory-by-medhisttype/",
  postUserLongTermIns: BASE_URL + "/api/UserLongTermIns/add-UserLongTermIns",
  getInsProvider: BASE_URL + "/api/InsProvider",
  getincometypes: BASE_URL + "/api/IncomeType/",
  postadduserincome: BASE_URL + "/api/UserIncome/add-UserIncome/",
  getexpensetypesbyFreqId:
    BASE_URL + "/api/Expense/get-expense-by-expenseFrequencyId",
  getPaymentMethod: BASE_URL+ "/api/PaymentMethod/get-PaymentMethod",
  getexpensetypes: BASE_URL + "/api/Expense/",
  postMonthlyExpenses: BASE_URL + "/api/UserIncome/add-user-expense",
  upsertMonthlyExpenses : BASE_URL + "/api/UserIncome/upsert-user-expense",
  getMonthlyExpensesDetails:
    BASE_URL + "/api/UserIncome/get-UserExpense-by-userid/",
  postNonMonthlyExpenses: BASE_URL + "/api/Expense",
  putNonMonthlyExpenses: BASE_URL + "/api/Expense",
  upsertNonMonthlyExpenses: BASE_URL + "/api/Expense/UpsertExpense",
  upsertMonthlyExpenses: BASE_URL + "/api/UserIncome/upsert-user-expense",

  getsubjectForFormLabelId:
    BASE_URL + "/api/Subject/get-subject-for-form-label-id",
  getInsPolicyType: BASE_URL + "/api/PolicyType",
  postaddLifeInsurance: BASE_URL + "/api/LifeInsurance/add-life-insurance",
  getBusinessType: BASE_URL + "/api/BusinessType/",
  getUserBusinessInterest:
    BASE_URL + "/api/UserBusinessInterest/get-UserBusinessInterest",
  postUserBusinessInterest:
    BASE_URL + "/api/UserBusinessInterest/add-UserBusinessInterest",
  updateUserBusinessInterest:
    BASE_URL + "/api/UserBusinessInterest/update-UserBusinessInterest",
  getLegalType: BASE_URL + "/api/LegalDoc/",
  getLegalDocument: BASE_URL + "/api/UserLegalDocument/",
  postLegalDocument: BASE_URL + "/api/UserLegalDocument/upsert-UserLegalDocument/",
  getFiduciaryAsgnmntType: BASE_URL + "/api/FiduciaryAsgnmntType",
  getFiduciarySRank: BASE_URL + "/api/FiduciarySRank",
  postFiduciaryAsmgentData:BASE_URL + "/api/UserFiduciaryAssignment/add-UserFiduciaryAssignment",
  getFiduciaryAsgnmntData:BASE_URL +"/api/UserFiduciaryAssignment/get-UserFiduciaryAssignment-by-UserId/",
  getCitizenshipType: BASE_URL + "/api/CitizenshipType",
  getSearchProfessionalV1: BASE_URL + "/api/Member/searchProfessionals",
  getSearchProfessional: BASE_URL + '/api/2/ProfessionalUser/getMemberProfessionals',
  getProfesType: BASE_URL + "/api/ProfessionalType",
  postaddprofessionluser:
    BASE_URL + "/api/ProfessionalUser/add-ProfessionalUser/",
  updateprofessionluser:
    BASE_URL + "/api/ProfessionalUser/update-ProfessionalUser",
  postaddusersubjectdata: BASE_URL + "/api/Subject/add-user-subject-data",
  getPreFrequency: BASE_URL + "/api/PreFrequency",
  getBeneficiaryByUserId:
    BASE_URL + "/api/Beneficiary/GetBeneficiaryListByUserId/",
  putupdateAddress: BASE_URL + "/api/Address/update-address-by-userid/",
  getSubjectResponse: BASE_URL + "/api/Subject/get-user-subject/",
  getSubjectV2Response: BASE_URL + "/api/Subject/get-user-subjectV2/",
  putSubjectResponse: BASE_URL + "/api/Subject/update-user-subject-data",
  deleteSubjectUser: BASE_URL + "/api/Subject/delete-user-subject-data-id",
  getFiduciaryforAssigment:
    BASE_URL + "/api/Fiduciary/GetFiduciaryListByUserId/",
  getUserMonthlyIncomePath:
    BASE_URL + "/api/UserIncome/get-UserIncome-by-userid/",
  getUserMonthlyExpensesPath:
    BASE_URL + "/api/UserIncome/get-UserExpense-by-userid/",
  putPrimaryCarePhysicianPath:
    BASE_URL + "/api/PrimaryCare/update-primarycaremember/",
  addOtherPath: BASE_URL + "/api/Others/add-others",
  mapOtherwithFormPath: BASE_URL + "/api/MemberOthersMap/add-member-othersmap",
  getOtherFromAPI: BASE_URL + "/api/MemberOthersMap/get-member-othersmap",
  updateOtherPath: BASE_URL + "/api/Others/update-others",
  // postaddprofessionluserMappingPath:
  //   BASE_URL + "/api/ProfessionalUser/add-ProfessionalUserMapping",
  getLongTermsInsType: BASE_URL + "/api/LongTermPolicyType",
  postFeedback: BASE_URL + "/api/Feedback/add-feedback",
  getMembersByParalegalIdPath: BASE_URL + "/api/Paralegal/getMembersByParalegalId/",
  getMembersByParalegalIdPathV2: BASE_URL + "/api/2/Paralegal/getMembersByParalegalId",
  getDocMembersByParalegalId: BASE_URL + "/api/2/Paralegal/getDocMembersByParalegalId",
  fileUploadPath: BASE_URL + "/api/FileUpload/uploadUserDocuments",
    fileUploadPath2: BASE_URL + "/api/2/FileUpload/uploadUserDocument",
    
  
  getUserbyId: BASE_URL + "/api/User/GetUserByUserId/",
  deleteVeteranByUserId: BASE_URL + "/api/Veteran/delete-veteran-by-userid/",
  getFileType: BASE_URL + "/api/FileType/GetFileTypeByCategory/",
  getFileCabinetType: BASE_URL + "/api/FileCabinet/GetFileCabinetList",
  postFileDocumentCabinetById:
    BASE_URL + "/api/FileCabinet/GetUserDocsByFileCabinet",
  postDownloadUserDocument: BASE_URL + "/api/FileUpload/downloadUserDocuments",
  postFileCabinetRemarksPath: BASE_URL + "/api/FileCabinet/addFileRemarks",
  getFileCabinetRemarksPath: BASE_URL + "/api/FileCabinet/getFileRemarks",
  putFileCabinetRemarksPath: BASE_URL + "/api/FileCabinet/updateFileRemarks",
  postUniversalSignUp: BASE_URL + "/api/User/RegisterUser",
  getCountryCode: BASE_URL + "/api/Country/GetRegistrationEnableCountry",
  postOtpData: BASE_URL + "/api/OTP/Validate-OTP-For-NewUser",
  postResendOtp: BASE_URL + "/api/OTP/ReSend-OTP-To-User",
  postForgotPassword: BASE_URL + "/api/User/SendEmailForForgotPassword",
  getAuthApiSettings: BASE_URL + "/api/Settings/authSettings",
  postAuth0UserLogin: BASE_URL + "/api/User/LogUserLogin",
  getUserDetailsByUSerID: BASE_URL + "/api/User/GetUserDetailsbyTokenKey/",
  postUpdateForgotPassword: BASE_URL + "/api/User/UpdateForgotPassword",
  getUserLongTermIns: BASE_URL + "/api/UserLongTermIns/",
  getLifeInsByUserId: BASE_URL + "/api/LifeInsurance/get-life-insurance/",
  putLifeInsByUserId: BASE_URL + "/api/LifeInsurance/update-life-insurance",
  getAthenticatePath: BASE_URL + "/api/User/AuthenticateLoggedInUser/",
  getLegalDocuments: BASE_URL + "/api/LegalDocument/getPrimaryDocuments",
  getLegalDocumentTree: BASE_URL + "/api/LegalDocument/getLegalDocuments/",
  getFiduciaryList: BASE_URL + "/api/Fiduciary/GetFiduciaryListByUserId/",
  postAgentUpsert: BASE_URL + "/api/UserAgent/upsertUserAgent",
  putUpdateTax: BASE_URL + "/api/UserTax/Update-UserTax/",
  getUserAgent: BASE_URL + "/api/UserAgent/getUserAgent",
  getNonFamilyMember: BASE_URL + "/api/Member/getUserNonFamilyMember/",
  getContractTemplatePath: BASE_URL + "/api/CEAuthorization/GetTemplates",
  getContractDetailPath: BASE_URL + "/api/CEAuthorization/GetContractDetails",
  createContractDetailPath:
    BASE_URL + "/api/CEAuthorization/CreateContractAsync",
  getContractDocumentPath: BASE_URL + "/api/CEAuthorization/DownloadDocument",
  getAsyncPath: BASE_URL + "/api/CEAuthorization/GetAsync/",
  postAsyncPath: BASE_URL + "/api/CEAuthorization/PostAsync/",
  createContract: BASE_URL + "/api/CEAuthorization/CreateContract/",
  updateAnswerPath: BASE_URL + "/api/CEAuthorization/UpdateAnswers/",
  putUserExpense: BASE_URL + "/api/UserIncome/update-user-expense",
  putUpdateUserAgingAsset: BASE_URL + "/api/UserAgingAsset/update-UserAgingAsset/",
  getAddressByaddressID: BASE_URL + "/api/Address/get-address/",
  postaddressAdd: BASE_URL + "/api/Address/add-address",
  updateaddressadd: BASE_URL + "/api/Address/update-address",
  deleteaddressadd: BASE_URL + "/api/Address/delete-address",
  createContract: BASE_URL + "/api/CEAuthorization/CreateContract/",
  updateAnswerPath: BASE_URL + "/api/CEAuthorization/UpdateAnswers/",
  putUserExpense: BASE_URL + "/api/UserIncome/update-user-expense",
  getInsCompany: BASE_URL + "/api/InsCompany/getInsCompany",
  getSubtenantDetails: BASE_URL + "/api/Subtenant/get-subtenant-details",
  userActivationLink: BASE_URL + "/api/UserActivation/SendUserActivationLink",
  postSendOtp: BASE_URL + "/api/OTP/Send-OTP-To-User",
  postActiveUser: BASE_URL + "/api/UserActivation/ActivateUser",
  postAddUser: BASE_URL + "/api/User/AddUser/",
  // postbulkfile: BASE_URL + "/api/User/CreateUsers",
  getTemplates: BASE_URL + "/api/CEAuthorization/GetTemplates",
  addUserContractId: BASE_URL + "/api/UserContract/AddUserContract",
  getUserContract: BASE_URL + "/api/UserContract/GetUserContract",
  postUserRole: BASE_URL + "/api/UserRole/AddRoleAsync/",
  putUserRole: BASE_URL + "/api/UserRole/UpdateRoleAsync",
  putUpsertLiabilitiy: BASE_URL + "/api/UserLiability/upsert-UserLiability",
  getPageCategory: BASE_URL + "/api/UserNotes/GetPageCategory",


  putFiduciaryAsmgentData:
    BASE_URL + "/api/UserFiduciaryAssignment/update-UserFiduciaryAssignment",
  getFileStatus: BASE_URL + "/api/FileCabinet/FileStatus?IsActive=true",
  getFileBelongsToPath: BASE_URL + "/api/FileCabinet/FileBelongsTo",
  // postAddFileCabinet: BASE_URL + "/api/UserFileCabinet/Add",
  postAddFileCabinet: BASE_URL + "/api/2/UserFileCabipnet/Add",
  postAddFileCabinet2: BASE_URL +  '/api/2/UserFileCabinet/Add',

  filecabinetPreparedByapi: BASE_URL + "/api/FileCabinet/PreparedBy/",
  filecabinetfilestatus: BASE_URL + "/api/FileCabinet/FileStatus",
  filecabinetdocument: BASE_URL + '/api/UserFileCabinet/Documents/',
  assessmentLetterUrl: BASE_URL + '/api/ProcessDocuments/UserAssessmentDoc/',
  roadmapLetterUrl: BASE_URL + '/api/ProcessDocuments/RoadmapDoc/',
  anualLetterUrl: BASE_URL + '/api/ProcessDocuments/UserAnnualMaintenanceDoc/',
  // postAddFileCabinet : BASE_URL + '/api/UserFileCabinet/Add',
  updateUserLongTerm: BASE_URL + '/api/UserLongTermIns/update-UserLongTermIns',
  getIsAuthUser: BASE_URL + '/api/UserAuth/IsAuthUser/',
  postbulkfile: BASE_URL + '/api/2/user/createusers/',
  postbulkfile: BASE_URL + '/api/2/user/createusers/',
  getAthenticatePath: BASE_URL + '/api/User/AuthenticateLoggedInUser/',
  // ipaddress:'https://geolocation-db.com/json/',
  // ipaddress:"https://ipinfo.io"
  // ipaddress:"https://api.db-ip.com/v2/free/self",
  getfileUploadDocuments: BASE_URL + "/api/FileUpload/documents/",
  postMemberAddress: BASE_URL + "/api/MemberAddress",
  putMemberAddress: BASE_URL + "/api/MemberAddress",
  putUserIncome: BASE_URL + '/api/UserIncome/update-UserIncome',
  upsertUserIncome: BASE_URL + '/api/UserIncome/upsert-UserIncome',
  mapUserInsurance: BASE_URL + '/api/UserInsuranceMap',
  mapUpdateInsurance: BASE_URL + '/api/UserInsuranceMap',
  mapPrimaryCare: BASE_URL + '/api/UserPrimaryCareMap',
  mapUpdatePrimaryCare: BASE_URL + '/api/UserPrimaryCareMap',
  mapGetPrimaryCare: BASE_URL + '/api/UserPrimaryCareMap/GetUserPrimaryCareMapAsync',
  getPrimaryCareMemberById: BASE_URL + '/api/PrimaryCare/get-primarycaremember-by-id',
  getUpsertetContact: BASE_URL + '/api/ImportedContact/GetupsertedContact',
  upsertSocialPeopleContact: BASE_URL + '/api/ImportedContact/upsertSocialPersonContact',
  getMemberStatus:BASE_URL+'/api/MemberStatus',
  checkLoginUserExist: BASE_URL + '/api/user/GetUserStatusByUserName/',
  resetPassword :BASE_URL + '/api/User/AddUserForgotPassword',
  updatePassword :BASE_URL + '/api/2/User/UpdateForgotPassword',
  getUserDetailByEmailId :BASE_URL + '/api/Account/GetUserDetailByEmailId?UserId',
  getUserDetailsByUSerID: BASE_URL + '/api/User/GetUserDetailsbyTokenKey/',
  getAttorneyNotesApi: BASE_URL + '/api/UserNotes/GetUserNotes',
  postAttorrneyNotesApi:BASE_URL + '/api/UserNotesComment/UpsertUserNotesComment',
  upsertMemberRelationship : BASE_URL + '/api/MemberRelationship/upsertMemberRelationship',





  getfileUploadDocuments: BASE_URL + "/api/FileUpload/documents/",
  postMemberAddress: BASE_URL + "/api/MemberAddress",
  putMemberAddress: BASE_URL + "/api/MemberAddress",

  getSubscriptionDetails: BASE_URL + "/api/Subscription/Details/",
  getUserListByRoleId: BASE_URL + "/api/User/getUserListByRoleId/",

  postuserSubscriptionAdd: BASE_URL + "/api/UserSubscriptions/add/",
  postUserAgreement: BASE_URL + "/api/UserAgreement/upsertUserAgreement",
  deleteUserAgreement: BASE_URL + "/api/UserAgreement/DeleteUserAgreement/",
  getUserAgreement: BASE_URL + "/api/UserAgreement/",
  postuserSubscriptionPlans: BASE_URL + "/api/UserSubscriptionPlans/add/",
  postusersubscriptionGeneratesDocs: BASE_URL + "/api/UserSubscriptions/GenerateDocs/",
  getUserSubscription: BASE_URL + "/api/UserSubscriptions/",
  getUserSubscriptionPlans: BASE_URL + "/api/UserSubscriptionPlans/GetUserSubscriptionPlansAsync",
  postuserlinkgenerate: BASE_URL + "/api/UserLinks/generate",
  getvalidateUserLinks:'/api/UserLinks/ValidateUserLink',
  putuserLinksUpdate: BASE_URL + "/api/UserLinks/update",
  putUserSubscriptionsetLink: BASE_URL + "/api/UserSubscriptions/setLink",
  // getpostCommMediumPath:BASE_URL+ '/api/CommMedium/GetCommMedium',
  getCommMediumPath: BASE_URL + '/api/CommMedium/GetCommMedium',
  GetEmailTemplate: BASE_URL + "/api/EmailTemplates/GetEmailTemplates",
  PostEmailCom: BASE_URL + "/api/EmailComm/SendEmailComm",
  getTextTemplate: BASE_URL + "/api/TextTemplates/GetTextTemplates",
  postSendTextPath: BASE_URL + '/api/TextComm/SendText',
  putUserSubUpdate: BASE_URL + '/api/UserSubscriptions/update',
  upsertuserSubscriptionPlans: BASE_URL + '/api/UserSubscriptionPlans/upsert',

  getsubdetails: BASE_URL + '/api/Subtenant/get-subtenant-details',
  getLiabilities: BASE_URL + '/api/Liability/',
  getUserLiabilityByUserRealPropertyId: BASE_URL + '/api/UserLiability/getUserLiabilityByUserRealPropertyId/',
  getAgentRankList: BASE_URL + '/api/UserAgentRank/getUserAgentRank',


  getsubdetails: BASE_URL + '/api/Subtenant/get-subtenant-details',
  deleteFileCabinetFileByFileId: BASE_URL + '/api/FileCabinet/DeleteFilebyFileId',
  userGenerateLinks: BASE_URL + '/api/UserLinks/generate',
  getJointAccountLink: BASE_URL + '/api/LinkedAccount/AddLinkedAccount',
  // getProfessionalUsers : BASE_URL + '/api/ProfessionalUser/Get-ProfessionalUsers',
  getProfessionalUsers : BASE_URL + '/api/2/ProfessionalUser/getProfessionalUsers',
  getProfessionalUsersV3 : BASE_URL + '/api/2/ProfessionalUser/getProfessionalUsersV3',
  postGetProfessionalUsersV3 : BASE_URL + '/api/2/ProfessionalUser/getProfessionalUserV3',
  getFiduciaryDetailsByUserId: BASE_URL + '/api/Fiduciary/GetFiduciaryDetailsByUserId/',
  getBeneficiaryDetailsByUserId: BASE_URL + '/api/Beneficiary/GetBeneficiaryDetailsByUserId/',
  getMarginalTaxRate : BASE_URL + '/api/TaxRate/get-marginal-tax-rate',
  deleteprofessionalUser:BASE_URL+'/api/ProfessionalUser/delete-user-professionalUser',
  getUserDetailsByUserEmailId:BASE_URL+'/api/Account/GetUserDetailByEmailId',
  deleteFidAssign : BASE_URL + '/api/UserFiduciaryAssignment/Delete-UserFiduciaryAssignment',
  deleteBussinessInterest : BASE_URL + '/api/UserBusinessInterest/detele-UserBusinessInterest',
  deleteUserLongTermIns : BASE_URL + '/api/UserLongTermIns/delete-UserLongTermIns/',
  deleteUserLiability : BASE_URL + '/api/UserLiability/Delete-UserLiability',
  deleteNonMonthlyExpense : BASE_URL + '/api/UserIncome/update-user-expense',
  deleteUserInsurance : BASE_URL + '/api/UserInsurance/Delete-UserInsurance',
 
  deleteProfessionalUser : BASE_URL + '/api/ProfessionalUser/delete-user-professionalUser',
  getProfessionalSecDesc : BASE_URL + '/api/ProfessionalSecDesc',
  // postProfessionalUserMapping : BASE_URL + '/api/ProfessionalUser/upsert-ProfessionalUserMapping',
  postProfessionalUserMapping : BASE_URL + '/api/2/ProfessionalUser/upsert-ProfessionalUserMapping',
  // postProfessionalUser : BASE_URL + '/api/ProfessionalUser/upsert-ProfessionalUser',
  postProfessionalUser : BASE_URL + '/api/2/ProfessionalUser/upsert-ProfessionalUser',
  getcontactdeailswithOther:BASE_URL+ "/api/Contact/get-contact-by-userid/",
  deleteSpecialistDatabyDocuserId:BASE_URL+ "/api/PrimaryCare/delete-primarycaremember-by-id",
  postMemberRelationship:BASE_URL+'/api/MemberRelationship/',
  getProffesionalSubType : BASE_URL + '/api/ProfessionalSubType',
  sendPostEmailCC:BASE_URL+'/api/EmailComm/SendEmailWithCCAsync',
  sendMailFeedBack:BASE_URL+'/api/EmailComm/SendEmailToMultipleNAttachmentAsync',
  updateMemberChildByUserId:BASE_URL+'/api/Member/update-memberChild-by-userId/',
  getUserAgentListPath:BASE_URL+ '/api/UserAgent/getUserAgent',
  getCommMediumPath:BASE_URL+ '/api/CommMedium/GetCommMedium',
  getProfessionalByUserIdPath:BASE_URL+ '/api/ProfessionalUser/Get-ProfessionalUser-By-UserId/',
  putProfessionaluserPath:BASE_URL+ "/api/ProfessionalUser/update-ProfessionalUser/",
  getNotifyContact:BASE_URL+'/api/NotifyContactMap/getNotifyContactMap/',
  getNotifyMessage:BASE_URL+'/api/NotifyMessage/getNotifyMessage/',
  postNofityMessage:BASE_URL+"/api/NotifyMessage/upsertNotifyMessage/",
  postcontactmap:BASE_URL+"/api/NotifyContactMap/upsertNotifyContactMap/",
  putusersubjectdata:BASE_URL+ '/api/Subject/update-user-subject-data',
  getUserAgentListPath:BASE_URL+ '/api/UserAgent/getUserAgent',

  GetEmailTemplate:BASE_URL+ "/api/EmailTemplates/GetEmailTemplates",
  PostEmailCom:BASE_URL+ "/api/EmailComm/SendEmailComm",
  getTextTemplate:BASE_URL+ "/api/TextTemplates/GetTextTemplates",
  postSendTextPath: BASE_URL+'/api/TextComm/SendText',
  getCommTypePath:BASE_URL+'/api/CommType',
  SendEmailCommPath:BASE_URL+"/api/EmailComm/SendEmailComm",
  getUserDetailsByEmailId:BASE_URL+'/api/Account/GetUserDetailByEmailId',
  userGenerateLinks:BASE_URL+'/api/UserLinks/generate',
  updateMemberChildByUserId:BASE_URL+'/api/Member/update-memberChild-by-userId/',
  getNotifyContact:BASE_URL+'/api/NotifyContactMap/getNotifyContactMap/',
  getNotifyMessage:BASE_URL+'/api/NotifyMessage/getNotifyMessage/',
  updateMemberChildByUserId:BASE_URL+'/api/Member/update-memberChild-by-userId/',
  getProfessionalByUserId:BASE_URL+'/api/ProfessionalUser/Get-ProfessionalUser-By-UserId/',
  getNotifyContact:BASE_URL+'/api/NotifyContactMap/getNotifyContactMap/',
  updateMemberChildByUserId:BASE_URL+'/api/Member/update-memberChild-by-userId/',
  getNotifyContact:BASE_URL+'/api/NotifyContactMap/getNotifyContactMap/',


  getProfessionalByUserIdPath:BASE_URL+ '/api/ProfessionalUser/Get-ProfessionalUser-By-UserId/',
  putProfessionaluserPath:BASE_URL+ "/api/ProfessionalUser/update-ProfessionalUser/",
  getNotifyContact:BASE_URL+'/api/NotifyContactMap/getNotifyContactMap/',
  getNotifyMessage:BASE_URL+'/api/NotifyMessage/getNotifyMessage/',
  postNofityMessage:BASE_URL+"/api/NotifyMessage/upsertNotifyMessage/",
  postcontactmap:BASE_URL+"/api/NotifyContactMap/upsertNotifyContactMap/",
  putusersubjectdata:BASE_URL+ '/api/Subject/update-user-subject-data',
  getVeteranData:BASE_URL+ "/api/Veteran/get-veteran-by-userid/",
  upsertNotifyContactMapApi:BASE_URL+'/api/NotifyContactMap/upsertNotifyContactMap',

  postAddUserOrder:BASE_URL+'/api/UserOrder/AddUserOrder/',
  getEnquiryMembers:BASE_URL+'/api/SeminarAttendee/getEnquirySeminarAttendee',
  upsertPlannerBooking:BASE_URL+'/api/PlannerBookings/upsertPlannerBookings/',
  updatePlannerBookingStatus:BASE_URL+'/api/PlannerBookings/updatePlannerBookingStatus',
  getUserActivationLink:BASE_URL+'/api/UserActivation/GetUserActivationLink',
  postAddUserOrder:BASE_URL+'/api/UserOrder/AddUserOrder/',
  postConfirmUserOrder:BASE_URL+'/api/UserOrder/ConfirmUserOrder/',
  getUserActivationLink:BASE_URL+'/api/UserActivation/GetUserActivationLink',
  putUserNameEmail:BASE_URL+'/api/Account/UpdateUserName',
  postaddprofessionluserMappingPath:BASE_URL + "/api/ProfessionalUser/add-ProfessionalUserMapping",


  getAllergiesType:BASE_URL+'/api/AllergiesType',
  getBloodType:BASE_URL+'/api/BloodType',
  GetEmerContactPriority:BASE_URL+'/api/EmerContactPriority/GetEmerContactPriority',
  upsertEmergencyCardApi:BASE_URL+'/api/EmergencyCard/UpsertEmergencyCard',
  getEmergencyApi:BASE_URL+'/api/EmergencyCard/GetEmergencyCard',
  getSocialPersonType:BASE_URL+'/api/SocialPersonType',
  deleteImportedContact:BASE_URL+'/api/ImportedContact/DeleteSocialPersonById',
  GetFeedbackPriority:BASE_URL+'/api/FeedbackPriority/GetFeedbackPriority',
  postClientHandOffUrl:BASE_URL+'/api/Member/ClientHandOff',
  UpsertUserMedication:BASE_URL+'/api/2/UserMedication/UpsertUserMedication',
  GetUserMedication:BASE_URL+'/api/2/UserMedication/GetUserMedication/',
  GetMedications:BASE_URL+'/api/2/UserMedication/GetMedication',
  getUserNotes:BASE_URL+ '/api/UserNotes/GetUserNotes',
  postUserNotes:BASE_URL+'/api/UserNotes/UpsertUserNotes',

  getIPv4: BASE_URL + "/api/CEAuthorization/get-ip",

  // payment card realted APIs
  postCardVerify: AoPaymentUrl + 'Catalog/CheckCreditCard',

  // CEXML file upload url
  postCEXMLfileUpload:BASE_URL+'/api/CEXML/uploadxmlfile',
  postCEXMLMemberData:BASE_URL+'/api/CEXML/UpdateMemberCEData',
  getCEXMLdata:BASE_URL+'/api/CEXML/GetMemberCEData',
  getCEXMLCheckMemberCeData:BASE_URL+'/api/CEXML/CheckMemberCEData',
  sentEmailWithAsyncCcBc:BASE_URL+'/api/EmailComm/SendEmailWithCCnBccAsync',
  getProfessionalsList:BASE_URL+'/api/2/ProfessionalUser/getMemberProfessionals',
  getFileCabinetFolderDetails:BASE_URL+ "/api/2/FileCabinet/GetFileCabinetFolderDetails",
  upsertCabinetFolder:BASE_URL+ '/api/2/FileCabinet/UpsertFileCabinetFolder',
  getDescountDetails:BASE_URL+'/api/Discount/GetDiscount',
  getEnumValuesType:BASE_URL+'/api/CEXML/GetEnumValues',
  get_RateCard:BASE_URL+'/api/RateCard/GetRateCard',
  get_Order_Info:BASE_URL+'/api/UserOrder/GetOrderInfo',
  post_CreateUserRecurringSubscription:BASE_URL+'/api/UserSubscriptions/CreateUserRecurringSubscription',
  get_UserProfileDetailsByUserId:BASE_URL+'/api/UserProfile/GetUserProfileByUserId/',
  get_subsModelForPaymentTime:BASE_URL+'/api/SubsModel/GetSubsModel',

  postRevokeLinkedAccount: BASE_URL + '/api/LinkedAccount/RevokeLinkedAccount',

  getparalegaluserdata:BASE_URL+'/api/2/User/GetUserCount',
  postLegalstaffdata:BASE_URL+'/api/UserLegalStaff/Upsert-UserLegalStaff',
  getCommMedium:BASE_URL+'/api/CommChannel/GetCommChannel',
  upsertUserMedHistory:BASE_URL+'/api/2/UserMedHistory/UpsertUserMedHistory',
  postLogUserout: BASE_URL + '/api/User/LogoutUser/',
  createAcademyUser:BASE_URL+'/api/User/CreateAcademyUser',

  getUserAgentByAgentId:BASE_URL+'/api/UserAgent/getUserByAgentId',

  deleteUserAccount: BASE_URL + '/api/User/delete-User',
  
  fetchAllCard: BASE_URL + '/api/UserProfile/SyncUserCardInfo',
  fetchUserServicePlan: BASE_URL + '/api/UserServicePlan/Get-User-Service-Plan-Values',
  getUniversalAddress: BASE_URL + '/api/Address/get-CountryDetails?countryName=',
};



export const Api_Url = {
  //  new file cabinet api --------------------------------------------------
  getMainCabinet: '/api/2/FileCabinet/GetMainCabinet',
  upsertMainCabinet: '/api/2/FileCabinet/UpsertMainCabinet',
  upsertCabinetCategoryType: '/api/2/FileCabinet/UpsertFileCategoryType',
  upsertCabinetFolder: '/api/2/FileCabinet/UpsertFileCabinetFolder',
  getFileCategoryTypeList: '/api/2/FileCabinet/GetFileCategoryTypeList',
  addFileCabinetFolder: "/api/2/FileCabinet/AddFileCabinetFolder",
  getSubtenantDetails: '/api/Subtenant/get-subtenant-details',
  getUserList: '/api/User/getUserList',
  fileBelongsTo: '/api/FileCabinet/FileBelongsTo',
  getFileCabinetFolderDetails: "/api/2/FileCabinet/GetFileCabinetFolderDetails",
  upsertCabinetFolderPermissions:'/api/2/FileCabinet/UpsertFolderPermissions',
  getFoldersPermissions:'/api/2/FileCabinet/GetFolderPermissions',
  // file url
  getFileTypeByCategory: '/api/2/FileCabinet/GetFileTypeList',
  postUploadUserDocument: '/api/FileUpload/uploadUserDocuments',
  putTaxInformation:"api/UserTax/Delete-UserTax",
  postUploadUserDocumentV2: '/api/2/FileUpload/uploadUserDocuments',
  
  
  addUserFileCabinet: '/api/2/UserFileCabinet/Add',
  getUserFileCabinetFile: '/api/2/UserFileCabinet/Documents/',
  getFileForView: '/api/FileUpload/downloadUserDocuments/',
  deleteFileCabinetFileByFileId: '/api/FileCabinet/DeleteFilebyFileId',

  //  / remarkls
  getFileCabinetRemarks: '/api/FileCabinet/getFileRemarks',
  postAddFileRemarks: '/api/FileCabinet/addFileRemarks',
  putUpdateFileRemarks: '/api/FileCabinet/updateFileRemarks',
  
  //  file share----------------------------------------------------------------------------
  upsertShareFileStatus:  '/api/2/UserFileCabinet/UpsertSharedFileStatus',
  getBeneficiaryList: '/api/Beneficiary/GetBeneficiaryListByUserId/',
  getFiduciaryList: '/api/Fiduciary/GetFiduciaryListByUserId/',
  getMemberProfessionals: '/api/2/ProfessionalUser/getMemberProfessionals',
  
  getSharedFileStatus:'/api/2/UserFileCabinet/GetSharedFileStatus',
  
  getUserListByRoleId:'/api/User/getUserListByRoleId',
  deleteFileCabinetFolder:'/api/2/FileCabinet/DeleteFolder/',

  
  checkInCabinetIsAnyLegalDoc:"/api/2/UserFileCabinet/CheckUserLegalDocument/",
  postEmail:'/api/EmailComm/SendEmailToMultipleNAttachmentAsync',  
  getBloodType:'/api/BloodType', 
  getFiduciaryDetailsListByUserId:"/api/Fiduciary/GetFiduciaryDetailsByUserId/" ,
  getBeneficiaryDetailsListByUserId:"/api/Beneficiary/GetBeneficiaryDetailsByUserId/" ,


  // LPO Annual Maintenance Plan ------------------------------------------------------------
    getUserSubscriptionsPath : "/api/UserSubscriptions/",
    getUserSubscriptionPlansPath : "/api/UserSubscriptionPlans/GetUserSubscriptionPlansAsync",
    getUserSaleableSkuPath : "/api/SaleableSKU/GetSaleableSKU",
    getCentralizedSubsTranscPath : "/api/CentralisedSubsTransaction/GetCentralisedSubsTransactions/",
    getUserProfilePath : "/api/UserProfile/GetUserProfileByUserId/",
    getRateCardPath : '/api/RateCard/GetRateCard',
    postUserProfile : '/api/UserProfile/UpsertUserProfile',
    postUserCard : '/api/UserProfile/SyncUserCardInfo',
    getUserOrderDetailsPath : '/api/UserSubscriptions/GetUserOrderDetails',
    getLoginUserDetailsPath : '/api/Account/GetLoginUserDetails',
    updateUserAuthSubscription : '/api/UserSubscriptions/UpdateUserAuthSubscription',
}



export let ipUrl = "https://geolocation-db.com/json";

export { $Service_Url };